### PR TITLE
Upgrade Mocha to remove install warnings

### PR DESCRIPTION
**Pull request by busches**
Upgrading to the latest Mocha removes the following warnings:

```
warning mocha > glob > minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue 
warning mocha > to-iso-string@0.0.2:to-iso-string has been deprecated, use @segment/to-iso-string instead.
warning mocha > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
```

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by busches** [comment]
Tests will fail until #9 is merged.

**Comment by busches** [comment]
Rebased.

**Comment by bcoe** [comment]
@busches thanks for the contribution 👍

**Pull request merged**
