### PR TITLE
Allow for running tests on Windows

### PR DESCRIPTION
**Pull request by busches**
This fixes running tests on Windows.

### CODE REVIEW

**Comment by bcoe** [comment]
@busches mind rebasing; looks like you have a timeout too; you might want to pull the 5s timeout out to 10s?

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by busches** [comment]
@bcoe I can rebase, I'm a bit confused on why this wasn't just merged, since it has the exact same fixes as #12 and was done a month earlier.

**Comment by busches** [comment]
Rebase is done.

**Comment by bcoe** [comment]
@busches don't suppose I could convince you to add an appveyor config 👍 

thanks a bunch for the contribution.

**Pull request merged**
